name: Add existing app or test app

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      url:
        description: Direct Download Url of .app or .zip file
        required: true
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: PowerShell

jobs:
  AddExistingAppOrTestApp:
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize the workflow
        id: init
<<<<<<< HEAD
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@preview
=======
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@v2.0
>>>>>>> 95de05c4a8c908def03cf21e7f32e451e975d3a2
        with:
          eventId: "DO0090"

      - name: Add existing app
<<<<<<< HEAD
        uses: microsoft/AL-Go-Actions/AddExistingApp@preview
=======
        uses: microsoft/AL-Go-Actions/AddExistingApp@v2.0
>>>>>>> 95de05c4a8c908def03cf21e7f32e451e975d3a2
        with:
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          url: ${{ github.event.inputs.url }}
          directCommit: ${{ github.event.inputs.directCommit }}

      - name: Finalize the workflow
<<<<<<< HEAD
        id: PostProcess
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@preview
=======
        if: always()
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@v2.0
>>>>>>> 95de05c4a8c908def03cf21e7f32e451e975d3a2
        with:
          eventId: "DO0090"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
